/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.quiz;

import it.unibo.quiz.gui.MenuGui;
import it.unibo.quiz.questions.JsonQuestionProvider;

public class App {

    public static void main(String[] args) {
        new MenuGui(new JsonQuestionProvider(ClassLoader.getSystemResourceAsStream("it/unibo/questions.json")));
    }
}
